gcp_project_id     = "<project-id>"
gcp_project_number = "<project-number>"
github_repository  = "<owner@id/repository@id>"
github_ref         = "<exact-ref>"
state_bucket_name  = "<globally-unique-state-bucket>"
